tag: "spectraformer:min54_ArithmLoss_multidata_highf_LRschedule"

#                  Min:             Base:
# embedding_dim:     64              256
# num_heads:          8               16
# num_layers:         2                8

embedding_dim: 64
num_heads: 8
num_layers: 2

learning_rate: 1e-3
learning_rate_decay: "Multiple cosine decay cycles" # one from the list ["Multiple cosine decay cycles","Constant"]
warmup_steps: 2250
decay_steps: 4500

num_cycles: 15 #changed from 100 to 20 after training for experiment
decline_coeff: 0.9

num_epochs: 100 #this is for a single run from (restored_epoch + 1) to (restored_epoch + configs.num_epochs) included
batch_size: 24 #should be divisible by 1, 2, 3, and 4 -- multiplication of 12.
dropout_rate: 0.5
root_rng_seed: 0

train_dataset:  "SiC_19x10x3" #"SiC_100x10"

log_every_epochs: 1

masked_interval_starts: [1000, 2500]
masked_interval_ends: [1660, 2900]
random_mask: False

mean: 'Arithmetic' # one from the list ['Arithmetic', 'Geometric']