tag: "spectraformer:min33_GeomLoss_LR3"
embedding_dim: 64
num_heads: 8
num_layers: 2
learning_rate: 1e-3
num_epochs: 600
batch_size: 19
dropout_rate: 0.5
root_rng_seed: 0
train_dataset:  "SiC_19x10x3" #"SiC_100x10"
log_every_epochs: 5
masked_interval_starts: [1000, 2500]
masked_interval_ends: [1660, 2900]
random_mask: False
mean: 'Geometric' # one from the list ['Arithmetic', 'Geometric']