tag: "spectraformer:min40_GeomLoss_LRSchedule_4cycles_decline1to1p6"
embedding_dim: 64
num_heads: 8
num_layers: 2

learning_rate: 1e-3
learning_rate_decay: "Multiple cosine decay cycles" # one from the list ["Multiple cosine decay cycles","Constant"]
warmup_steps: 2250
decay_steps: 4500

num_cycles: 100
decline_coeff: 0.625

num_epochs: 1200
batch_size: 19
dropout_rate: 0.5
root_rng_seed: 0

train_dataset:  "SiC_19x10x3" #"SiC_100x10"

log_every_epochs: 5

masked_interval_starts: [1000, 2500]
masked_interval_ends: [1660, 2900]
random_mask: False

mean: 'Geometric' # one from the list ['Arithmetic', 'Geometric']